### ISSUE TITLE
tensor_utils.DTYPE_MAP is incompatible with Numpy 1.24

### ISSUE THREAD

**Issue by rusheb** [mivanit/muutils#1]
## Problem
If Numpy 1.24 is installed then importing [`tensor_utils.DTYPE_MAP`](/mivanit/muutils/blob/4a9dae2d6fd51b9f30de47fdb1be0a87a8ad597b/muutils/tensor_utils.py#L52) fails:
```bash
❯ pip freeze | grep numpy
numpy==1.24.1
❯ python3
Python 3.10.6 (main, Nov 13 2022, 09:18:28) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from muutils.tensor_utils import DTYPE_MAP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rusheb/code/tmp/venv/lib/python3.10/site-packages/muutils/tensor_utils.py", line 69, in <module>
    np.float_, np.float16, np.float32, np.float64, np.half, np.float, np.double,
  File "/Users/rusheb/.pyenv/versions/3.10.6/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
>>>
```

## Explanation
The deprecation of the `numpy.float` dtype [expired as of Numpy 1.24.0](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations).

The release notes also mention `np.object`, `np.bool`, `np.float`, `np.complex`, `np.str`, and `np.int`.

`np.long` is not mentioned but I also get "No definition found" when I try to jump to definition in vs code.

## Workaround
Bumping down to numpy 1.23 resolves the issue

```bash
❯ pip install --force-reinstall -v "numpy==1.23.1"
Using pip 23.0 from /Users/rusheb/code/tmp/venv/lib/python3.10/site-packages/pip (python 3.10)
Collecting numpy==1.23.1
  Using cached numpy-1.23.1-cp310-cp310-macosx_11_0_arm64.whl (13.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.1
    Not uninstalling numpy at /Users/rusheb/.pyenv/versions/3.10.6/lib/python3.10/site-packages, outside environment /Users/rusheb/code/tmp/venv
    Can't uninstall 'numpy'. No files were found to uninstall.
  changing mode of /Users/rusheb/code/tmp/venv/bin/f2py to 755
  changing mode of /Users/rusheb/code/tmp/venv/bin/f2py3 to 755
  changing mode of /Users/rusheb/code/tmp/venv/bin/f2py3.10 to 755
Successfully installed numpy-1.23.1
❯ pip freeze | grep numpy
numpy==1.23.1
❯ python3
Python 3.10.6 (main, Nov 13 2022, 09:18:28) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from muutils.tensor_utils import DTYPE_MAP
>>>
```

## Remediation
I'm not sure what the best choice is between a few options:
* Simply remove `np.float` and other deprecated dtypes from [`DTYPE_MAP`](/mivanit/muutils/blob/4a9dae2d6fd51b9f30de47fdb1be0a87a8ad597b/muutils/tensor_utils.py#L68-L77)
  * May cause compatibility issues for users running older numpy versions
* Release a numpy-1.24 version of this library
  * Adds complexity but prevents breaking client code
* Add a conditional check on whether the dtype exists
  * Avoids managing library versions and breaking clients, but pretty hacky and would not scale

I'm also not sure if there are other compatibility issues that haven't surfaced yet.

**Comment by mivanit** [comment]
I've fixed this in the [`dev`](https://github.com/mivanit/muutils/tree/dev) branch, which should probably be merged into main ASAP. Given that noone other than myself uses this library, I don't think we need to worry about backward compatibility just yet
