### ISSUE TITLE
Type hints incompatible with python 3.8

### ISSUE THREAD

**Issue by rusheb** [mivanit/muutils#14]
Due to using python 3.9+ lowercase type hints for collections, muutils is no longer compatible with python 3.8.

I think this is the relevant PEP: https://peps.python.org/pep-0585/ 

The consequence is that that muutils cannot be imported into colab or by any consumer using python < 3.9

We could solve this in 1 of 2 ways:

* add `from __future__ import annotations` to the start of each muutils file
* replace lowercase type hints with upper case ones (e.g. `dict[str, int] -> Dict[str, int]`)

~~I think it would be worth setting up CI to run the unit tests for all supported python minor versions (namely 3.8, 3.9, 3.10, 3.11). This feels like it might be overkill in terms of engineering effort and actions minutes used. on the other hand these compatibility issues are a huge PITA!~~ edit: struck out because there was already an issue for this (#9)

@mivanit thoughts?

**Comment by rusheb** [comment]
I've set up CI for python 3.10 and 3.11. 

I'm looking into ways of running python >=3.10 in colab.  This [s/o answer](https://stackoverflow.com/a/74538231/6631502) looks promising.

It's very hacky though, and people report instability in the comments, so we should probably still try to get compatibility with 3.8

**Comment by rusheb** [comment]
I've started to work on this issue on branch [rusheb-python-3.8](../tree/rusheb-python-3.8)

**Comment by mivanit** [comment]
(copy from slack)

So it looks like an easier solution might just be to include in (colab) notebooks the following to update the python version:
```ipynb
!wget https://github.com/korakot/kora/releases/download/v0.10/py310.sh
!bash ./py310.sh -b -f -p /usr/local
!python -m ipykernel install --name "py310" --user

import sys
print("version:", sys.version)
```

source: https://stackoverflow.com/questions/70141277/is-it-possible-to-use-python-3-10-in-google-colab
