### ISSUE TITLE
clearer alternative to `loading_fn`

### ISSUE THREAD

**Issue by mivanit** [mivanit/muutils#40]
`serializeable_field()` currently takes a `loading_fn` parameter, which, due to a dumb choice by me ages ago, takes directly the dict representing the whole object instead of the actual field we care about. this makes code a bit messy. It was originally to allow for extracting data from other fields in the object, but this is bad practice. Currently, the syntax looks like:

```python
@serializable_dataclass
class MyClass(SerializableDataclass):
  some_field: int = serializable_field(
    serialization_fn = lambda x : str(x),
    loading_fn = lambda x : int(x["some_field"])
  )
```

Changing the behavior of the existing function would probably be a bad idea, so I think the best course of action is to create a new parameter, perhaps `deserialization_fn`, which allows us to do
```python
deserialization_fn = lambda x : int(x)
```

This should be a change of just a few lines in `muutils.json_serialize.serializable_dataclass`

**Comment by kevinlu1248** [comment]
Hey I'm a developer of Sweep. Just letting you now I'm taking a look at this issue.

**Comment by kevinlu1248** [comment]
Can you merge the above PR? It's a trivial change to bump the commit hash which causes Sweept to re-index

**Comment by kevinlu1248** [comment]
sweep: Retry
